version: "3"
services:
  catalog:
    build: containers/dev
    command: /bin/sh -c 'stack build && stack install && stack exec catalog-exe'
    volumes:
      - .:/catalog
    working_dir: /catalog
    ports:
      - 8080:8080

  catalog-db:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: master
      POSTGRES_DB: catalog
    ports:
      - 54332:5432
